name: CI
run-name: ${{ github.actor }}'s CI management
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install opam
      - run: opam init --yes
      - run: eval $(opam env --switch=default)
      - run: opam repo add --yes --this-switch coq-released https://coq.inria.fr/opam/released
      - run: opam repo add --yes --this-switch iris-dev https://gitlab.mpi-sws.org/iris/opam.git
      - run: opam pin --yes -n coq-sail-stdpp https://github.com/rems-project/coq-sail.git#f319aad
      - run: opam install --yes ./coq-cheri-capabilities.opam
      - run: eval $(opam env)

